on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  testcpp:
    name: Test C++
    runs-on: ubuntu-22.04
    container:
      image: klalumiere/ubuntu-clang:22-14
    strategy:
      matrix:
        buildType: [
          Debug,
          RelWithDebInfo,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare environment
        env:
            DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get install --assume-yes --no-install-recommends libclang-14-dev llvm-14-dev
      - name: Run Tests
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{matrix.buildType}} -B build -S .
          cmake --build build

          cmake \
            -D CMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -B buildRepoUsingPlugin -S repo-using-plugin
          cmake --build buildRepoUsingPlugin

          clang-tidy \
            --checks='awesomeprefixcheck' \
            --load build/lib/libAwesomePrefixCheck.so \
            -p buildRepoUsingPlugin/compile_commands.json \
            repo-using-plugin/src/code.cpp
